### ISSUE TITLE
Tune issues from Neil C.

### ISSUE THREAD

**Issue by tcizadlo** [slow-session/wellington.session.nz#148]
OTHER GLITCHES
B part has right repeat, but no left repeat (returns to beginning of
tune without repeat):
Billowing Waves
Congress Reel
Cuil Aodha Slide (plus usual two-line problem)

Tune written in semiquavers rather than quavers, so plays too fast:
Bonnie Ann
Carina Normansson's Polska
Cylinder Kontra fra Min
Dal Jerks Gaanglaat
Duke of Gordon's Birthday (some semiquavers - borderline)
Evenesdalingen

Key assignment:
Brosna Slide: "D slide", but actually in G
Cup of Tea: Two pages - one says E dor, other D maj, but they are in
the same key (E dor in A part, D maj in B&C parts)
Morning Star music: 2 sharps in the key signature, but is in G - could
be either major or (hypothetically) Lydian, since neither C nor C#
occurs

Assorted ABC:
The Braes of Tulliemet: Multiple problems - needs left repeat,
two-line problem (in an unusual form), bass and treble clefs not
aligned on page, borderline speed problem with semiquavers.
Calliope House: Third line, bar 5 - F# an octave high. Bar 6 - D an octave low
The Dark Island: as well as the usual two line problem, treble and
bass are not properly aligned on the page.

Recordings:
The Road To Lisdoonvarna: Recording plays ABA, doesn't do B the second time.
The Rakes Of Kildare: I'm a bit conflicted on this one. It's a lovely
version, and I can't find it anywhere else on the net, but the slow
start stuffs up attempts to play at full tempo from the start. Would
we be allowed two recordings - this, and one with a consistent tempo?

Spelling:
Fourty Two Pound Cheque: Fourty > Forty, unless the Irish spell it
that way. Mind you, I think it's a damned stupid trick spelling
"fourteen", but "forty".

**Comment by asjl** [comment]
Did these all get sorted?

**Comment by asjl** [comment]
close #148
